export const EQUIPMENT_TYPES = [
  {
    id: "van",
    label: "Dry Van",
    cargoFields: ["crgo_genfreight", "crgo_paperprod"],
  },
  {
    id: "reefer",
    label: "Reefer",
    cargoFields: ["crgo_coldfood", "crgo_produce", "crgo_meat", "crgo_beverages"],
  },
  {
    id: "flatbed",
    label: "Flatbed",
    cargoFields: ["crgo_bldgmat", "crgo_metalsheet", "crgo_machlrg", "crgo_construct"],
  },
  {
    id: "stepdeck",
    label: "Step Deck",
    cargoFields: ["crgo_machlrg", "crgo_construct", "crgo_bldgmat"],
  },
  {
    id: "poweronly",
    label: "Power Only",
    cargoFields: ["crgo_genfreight", "crgo_intermodal"],
  },
  {
    id: "hopper",
    label: "Hopper Bottom",
    cargoFields: ["crgo_grainfeed", "crgo_drybulk", "crgo_coalcoke"],
  },
  {
    id: "tanker",
    label: "Tanker",
    cargoFields: ["crgo_liqgas", "crgo_chem"],
  },
  {
    id: "intermodal",
    label: "Intermodal / Container",
    cargoFields: ["crgo_intermodal"],
  },
  {
    id: "auto",
    label: "Auto Carrier",
    cargoFields: ["crgo_motoveh", "crgo_drivetow"],
  },
  {
    id: "livestock",
    label: "Livestock",
    cargoFields: ["crgo_livestock"],
  },
  {
    id: "logging",
    label: "Logging / Poles",
    cargoFields: ["crgo_logpole"],
  },
  {
    id: "dump",
    label: "Dump",
    cargoFields: ["crgo_garbage", "crgo_coalcoke"],
  },
  {
    id: "oilfield",
    label: "Oilfield",
    cargoFields: ["crgo_oilfield"],
  },
  {
    id: "household",
    label: "Household Goods",
    cargoFields: ["crgo_household"],
  },
  {
    id: "hazmat",
    label: "Hazmat / Chemicals",
    cargoFields: ["crgo_chem", "crgo_liqgas"],
  },
];

export const CARGO_LABELS = {
  crgo_genfreight: "General Freight",
  crgo_household: "Household Goods",
  crgo_metalsheet: "Metal / Sheet",
  crgo_motoveh: "Motor Vehicles",
  crgo_drivetow: "Driveaway / Towaway",
  crgo_logpole: "Logs / Poles",
  crgo_bldgmat: "Building Materials",
  crgo_mobilehome: "Mobile Homes",
  crgo_machlrg: "Machinery / Large Objects",
  crgo_produce: "Produce",
  crgo_liqgas: "Liquids / Gases",
  crgo_intermodal: "Intermodal",
  crgo_passengers: "Passengers",
  crgo_oilfield: "Oilfield",
  crgo_livestock: "Livestock",
  crgo_grainfeed: "Grain / Feed",
  crgo_coalcoke: "Coal / Coke",
  crgo_meat: "Meat",
  crgo_garbage: "Garbage / Refuse",
  crgo_usmail: "US Mail",
  crgo_chem: "Chemicals",
  crgo_drybulk: "Dry Bulk",
  crgo_coldfood: "Refrigerated Food",
  crgo_beverages: "Beverages",
  crgo_paperprod: "Paper Products",
  crgo_utility: "Utilities",
  crgo_farmsupp: "Farm Supplies",
  crgo_construct: "Construction",
  crgo_waterwell: "Water Well",
};

export const CARGO_FIELDS = Object.keys(CARGO_LABELS);

export const EXTRA_CENSUS_FIELDS = [
  "fax",
  "company_officer_2",
  "add_date",
  "dun_bradstreet_no",
  "mcs150_mileage_year",
  "bus_units",
  "fleetsize",
  "total_cdl",
  "total_intrastate_drivers",
  "driver_inter_total",
  "avg_drivers_leased_per_month",
  "interstate_beyond_100_miles",
  "interstate_within_100_miles",
  "intrastate_beyond_100_miles",
  "intrastate_within_100_miles",
  "safety_rating_date",
  "review_type",
  "review_date",
  "recordable_crash_rate",
  "prior_revoke_dot_number",
  "mcsipdate",
  "carrier_mailing_street",
  "carrier_mailing_city",
  "carrier_mailing_state",
  "carrier_mailing_zip",
  "carrier_mailing_country",
  "owntruck",
  "owntract",
  "owntrail",
  "trmtruck",
  "trmtract",
  "trmtrail",
  "trptruck",
  "trptract",
  "trptrail",
];

export const SELECT_FIELDS = [
  "dot_number",
  "legal_name",
  "dba_name",
  "phone",
  "cell_phone",
  "email_address",
  "phy_street",
  "phy_city",
  "phy_state",
  "phy_zip",
  "phy_country",
  "docket1prefix",
  "docket1",
  "docket1_status_code",
  "docket2prefix",
  "docket2",
  "docket2_status_code",
  "docket3prefix",
  "docket3",
  "docket3_status_code",
  "status_code",
  "classdef",
  "truck_units",
  "power_units",
  "total_drivers",
  "safety_rating",
  "hm_ind",
  "company_officer_1",
  "business_org_desc",
  "carrier_operation",
  "mcs150_date",
  "mcs150_mileage",
  "prior_revoke_flag",
  "mcsipstep",
  ...EXTRA_CENSUS_FIELDS,
  ...CARGO_FIELDS,
];

export const OOS_MCSIP_STEPS = [
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
];
