export const SEARCH_MODES = [
  {
    id: "mc-range",
    label: "MC Range",
    description: "Scan a start–end Motor Carrier number range.",
  },
  {
    id: "mc-lookup",
    label: "Single MC / DOT",
    description: "Look up one MC or USDOT number.",
  },
  {
    id: "id-list",
    label: "MC / DOT list",
    description: "Paste many MC or USDOT numbers at once.",
  },
  {
    id: "company-name",
    label: "Company name",
    description: "Search legal name or DBA.",
  },
  {
    id: "location",
    label: "State & city",
    description: "Find active carriers by domicile.",
  },
  {
    id: "phone",
    label: "Phone number",
    description: "Match a phone or cell number on file.",
  },
];

export const SAFETY_RATINGS = [
  { id: "any", label: "Any safety rating" },
  { id: "usable", label: "Satisfactory or not rated" },
  { id: "S", label: "Satisfactory" },
  { id: "C", label: "Conditional" },
  { id: "U", label: "Unsatisfactory" },
  { id: "none", label: "Not rated" },
];

export const FLEET_PRESETS = [
  { id: "any", label: "Any size", minTrucks: "", maxTrucks: "" },
  { id: "oo", label: "Owner-op (1)", minTrucks: "1", maxTrucks: "1" },
  { id: "small", label: "Small (2–5)", minTrucks: "2", maxTrucks: "5" },
  { id: "mid", label: "Mid (6–15)", minTrucks: "6", maxTrucks: "15" },
  { id: "large", label: "Large (16+)", minTrucks: "16", maxTrucks: "" },
];

export const MCS150_OPTIONS = [
  { id: "any", label: "Any MCS-150 date" },
  { id: "12", label: "Updated in last 12 months" },
  { id: "24", label: "Updated in last 24 months" },
];

export const US_STATES = [
  ["AL", "Alabama"],
  ["AK", "Alaska"],
  ["AZ", "Arizona"],
  ["AR", "Arkansas"],
  ["CA", "California"],
  ["CO", "Colorado"],
  ["CT", "Connecticut"],
  ["DE", "Delaware"],
  ["DC", "District of Columbia"],
  ["FL", "Florida"],
  ["GA", "Georgia"],
  ["HI", "Hawaii"],
  ["ID", "Idaho"],
  ["IL", "Illinois"],
  ["IN", "Indiana"],
  ["IA", "Iowa"],
  ["KS", "Kansas"],
  ["KY", "Kentucky"],
  ["LA", "Louisiana"],
  ["ME", "Maine"],
  ["MD", "Maryland"],
  ["MA", "Massachusetts"],
  ["MI", "Michigan"],
  ["MN", "Minnesota"],
  ["MS", "Mississippi"],
  ["MO", "Missouri"],
  ["MT", "Montana"],
  ["NE", "Nebraska"],
  ["NV", "Nevada"],
  ["NH", "New Hampshire"],
  ["NJ", "New Jersey"],
  ["NM", "New Mexico"],
  ["NY", "New York"],
  ["NC", "North Carolina"],
  ["ND", "North Dakota"],
  ["OH", "Ohio"],
  ["OK", "Oklahoma"],
  ["OR", "Oregon"],
  ["PA", "Pennsylvania"],
  ["RI", "Rhode Island"],
  ["SC", "South Carolina"],
  ["SD", "South Dakota"],
  ["TN", "Tennessee"],
  ["TX", "Texas"],
  ["UT", "Utah"],
  ["VT", "Vermont"],
  ["VA", "Virginia"],
  ["WA", "Washington"],
  ["WV", "West Virginia"],
  ["WI", "Wisconsin"],
  ["WY", "Wyoming"],
];
